# Generated by Django 2.0.4 on 2018-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180422_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
